
services:
  backend:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - my-network
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge